version: "3.9"
services:
  server:
    build: server/
    ports:
      - 8099:3001
    env_file:
      - "server/.env"

  client:
    build: client/
    ports:
      - 8080:3000
    env_file:
      - "client/.env"
    depends_on:
      - server

networks:
  local:
    driver: "bridge"
