import type { Metadata } from "next";
import "@/shared/styles/globals.scss";
import clsx from "clsx";
import { RobotoFont, RubikFont } from "@/shared/styles/fonts";
import { EffectorNext } from "@effector/next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(RobotoFont.variable, RubikFont.variable)}>
        {children}
      </body>
    </html>
  );
}
